### ISSUE TITLE
Awknowledgements

### ISSUE THREAD

**Issue by dotMorten** [BHare1985/ArcGISRuntimeWKT#5]
It's pretty clear this is a fork of https://github.com/SharpMap/SharpMap/tree/Branches/1.0/SharpMap/Converters/WellKnownText

As required by that license, you should add the acknowledgements and state this is a derived work to the header of each source file. Basically be a good Open Source citizen :-)

**Comment by BHare1985** [comment]
Hey,

You are definitely correct. In my https://github.com/BHare1985/ArcGISRuntimeWKT/blob/master/ATTRIBUTIONS file I stated the project was derived off Esri Silverlight Wkt Parser which in turn was from your code and geotools.net. I included the license as I saw best.

I interpret and abide by the convention that the LGPL only strongly suggests a copy in each source file, but there is no legal requirement to do so in every file as long as its in the repository. I recall specifically looking up various discussions on the topic and while I feel a lot of people feel like having a copy in each source file is overkill and ugly (myself included) I know that some tend to air on the side of caution and include it in every source file.

As you are the one of the original license holders, I will abide by your recommendation if you feel my sole attributions file is not enough.

Let me know
